### ISSUE TITLE
Bulk transfer failed when client pagesize is 4KB and OSS pagesize is 64KB.

### ISSUE THREAD

**Issue by guojun85** [lustre/lustre-release#1]

**Comment by guojun85** [comment]
When client pagesize is 4KB and OSS pagesize is 64KB, the last bulk size will probably different and client and OSS, which will lead to bulk transfer failed.

**Comment by adilger** [comment]
Hello, please file your ticket at https://jira.Whamcloud.com/ since nobody is reviewing tickets here.
